### ISSUE TITLE
No login after installing the plugin

### ISSUE THREAD

**Issue by marcus-at-localhost** [spletnik/snoopy#1]
Hi, 
I installed your plugin and then a PIWIK user with admin rights, wasn't able to login anymore. Login screen said he cannot access resources without superadmin rights.

Any idea? Thanks!

**Comment by bsuligoj** [comment]
Hi Marcus,

We didn't experience any problems with installing plugin. Could you please provide us more information on issue. Did any error occurred on installation? Could you send us some screenshots of the error.

(If you managed to fix the problem yourself, could you please provide use with information  where the problem lied and how did you resolved it)

Best regards,
    Branko

**Comment by marcus-at-localhost** [comment]
I activated the plugin in the backend - everything was fine for me. Another user who has "just" admin rights wasn't able to login anymore and saw this screen

![2016-01-26_23-54-01](https://cloud.githubusercontent.com/assets/1337223/12598047/47a91156-c488-11e5-83d4-4f1753a19869.png)

Something like "Error: you can't access this resource, because it needs "superuser" right" - or so.

After deactivating the plugin he was able to login.

Unfortunately I don't know enough about piwiks plug in api.

**Comment by bsuligoj** [comment]
Hi,

We've just published updated version which should fix your problem but only superusers will be able to see the report until we find permanent solution.

Best regards,
    Branko

**Comment by marcus-at-localhost** [comment]
Thanks for the fixes! Looks good so far!
