### ISSUE TITLE
No Goals

### ISSUE THREAD

**Issue by marcus-at-localhost** [spletnik/snoopy#2]
Here is another bug:
in **Settings.php** on line 170
`$this->matching_goals->availableValues = array_merge(array('0' => 'None'), $options);`
array_merge re-index the numeric array with the goal ids, so they are never right (I delete goals so my ids are not sequential anymore).
It's rather:
`$this->matching_goals->availableValues = array('0' => 'None')+$options;`
Now I can select the goals with the right ids from the multiselect field in the plugin settings.

**Comment by bsuligoj** [comment]
Thanks for your feedback and bugfixes, we'll implement suggested changes as soon as possible.

Best regards,
   Branko
