### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by marcus-at-localhost** [spletnik/snoopy#4]
I don't see how I can make a connection from the piwik visitor id to the userid or email (if I record email) in the reports. Does it need some tweaks on the report class? If so, how?
Thanks!

**Comment by bsuligoj** [comment]
Hello Marcus,

First let me thank you for all your feedback, we'll try to implement your fixes as soon as possible. 

To match visitor with email, you have to provide data for specific visitorid. The easiest way to do this is with provided [API Call](https://github.com/spletnik/snoopy-behavioral-scoring/wiki/API#snoopybehavioralscoringstorevisitordata-idvisitor-data). When your visitor for example submit a form, you post data to piwik with visitorid and other data for visitor (field custom_1 is reserved for email).

When this is done, your visitors should be shown with their email's in Scores menu.

If you want emails/scores in default reports provided by piwik than you need to modify the views.

Let us know if you need any help with that.

Best regards,
    Branko

**Comment by marcus-at-localhost** [comment]
Thanks Branko for the input.
I ignored the part of the Snoopy Api Calls :) - I expected that your plugin is magically able to work with data that's already recorded, like in my case the userId as described here: http://piwik.org/docs/user-id/
I think if you could implement this connection to userid (if userid is recorded) that would already help, to make sense out of the score without setting up new api calls in an application. And from there on I can start recording more data. If that makes sense.

But I'll have a look at the API and how to override the report view.

Thanks!
